### ISSUE TITLE
Mobile collapse navbar does not respond

### ISSUE THREAD

**Issue by georules** [derbyjs/derby-site#13]
The collapsed bootstrap navbar 'hamburger' does not seem to execute the collapse functionality.  Is this because collapse is not implemented in d-bootstrap yet?  What would be the correct way to fix this?  (I'd like to help, but pretty new to derby.)

**Comment by nateps** [comment]
I suspect you may be correct that d-bootstrap doesn't implement most of bootstrap's javascript. This could be opened as a pull request on that repo, but I'm not actively maintaining it right now.

Closing this in order to clean up issues on derby-site. Thanks!
