### ISSUE TITLE
Homepage doesn't communicate how awesome the realtime collaboration is

### ISSUE THREAD

**Issue by zmillman** [derbyjs/derby-site#25]
Unless a visitor opens a new page or there happens to be another visitor simultaneously playing with the sliders, there's no way to see that it is actually collaborative.

I'm pretty sure that's the killer framework feature and I didn't understand that's what it did on my first several visits to the page. I thought "Oh, I guess this is just like Angular?" and moved on.

Adding a blurb asking visitors to try it in two tabs with a `target="_blank"` link would help a ton :smile:

**Comment by lazaridis-com** [comment]
I agree 100% with @zmillman. Is this repo actually monitored by the team / product-management?

**Comment by nateps** [comment]
Good suggestion! This was added.
